version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: dnd_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dnddb
    ports:
      - "5432:5432"   # если занят, поставь "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: