name: Deploy

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  REGISTRY_OWNER: ZenCoderDev

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment:
      name: production
      url: https://tbdices.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Copy build to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: |
            package.json
            package-lock.json
            .next/**
          target: /var/www/tbdices_com_usr/data/www/tbdices.com
          strip_components: 0

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ env.REGISTRY_OWNER }} --password-stdin
            
            set -e  # Прерывать при любой ошибке
            cd /var/www/tbdices_com_usr/data/www/tbdices.com

            echo "Starting PostgreSQL container..."
            docker compose -f docker-compose.yml up -d postgres

            echo "Waiting for PostgreSQL to be ready..."
            sleep 5

            echo "Installing production dependencies..."
            npm ci --production

            echo "Applying Prisma migrations..."
            npx prisma migrate deploy

            echo "Starting or restarting Next.js with PM2..."
            if pm2 list | grep -q "tbdices"; then
              pm2 restart tbdices
            else
              pm2 start npm --name "tbdices" -- start
            fi

            echo "Starting Prisma Studio..."
            if pm2 list | grep -q "prisma-studio"; then
              pm2 restart prisma-studio
            else
              pm2 start "npx prisma studio --port 5555 --browser none" --name "prisma-studio"
            fi


            pm2 save
           
            echo "Deployment finished successfully!"