name: Deploy

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  REGISTRY_OWNER: zencoderdev

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment:
      name: production
      url: https://tbdices.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: "."
          target: "/var/www/tbdices_com_usr/data/www/tbdices.com"
          strip_components: 0

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ env.REGISTRY_OWNER }} --password-stdin
            cd /var/www/tbdices_com_usr/data/www/tbdices.com
            
            docker compose -f docker-compose.prod.yml up -d db

            sleep 5

            npm install

            npx prisma migrate deploy

            if pm2 list | grep -q "tbdices"; then
              pm2 restart tbdices
            else
              pm2 start npm --name "tbdices" -- start
            fi